#!/usr/bin/env bash
cd "$(dirname "$0")/.."

export NODE_ENV="development"

./node_modules/.bin/concurrently \
    --prefix "{name}" \
    --names "server,test" \
    "./node_modules/.bin/nodemon --exec \"./node_modules/.bin/node\" --watch server ./server/index.js" \
    "NODE_ENV=test ./node_modules/.bin/jest --watchAll"
