#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."

rm -rf src/generated
mkdir -p src/generated
./node_modules/.bin/ts-node --project scripts/file-generators/tsconfig.json scripts/file-generators/generate-build-information.ts
./node_modules/.bin/ts-node --project scripts/file-generators/tsconfig.json scripts/file-generators/generate-raw.ts
./node_modules/.bin/ts-node --project scripts/file-generators/tsconfig.json scripts/file-generators/generate-rss.ts
