#!/usr/bin/env bash -e
cd "$(dirname "$0")"

npx ts-node --project file-generators/tsconfig.json ./file-generators/generate-build-info.ts
npx ts-node --project file-generators/tsconfig.json ./file-generators/generate-rss.ts
