#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."

echo "[BLOG] running type checks"
./node_modules/.bin/tsc --noEmit --project "tsconfig.json"
./node_modules/.bin/tsc --noEmit --project "scripts/file-generators/tsconfig.json"

echo "[BLOG] running prettier"
./node_modules/.bin/prettier --check "{src,public,scripts}/**/*.{ts,tsx,js,jsx,html,css}"

# CI=true runs tests as regular script instead of in watch mode
CI=true ./scripts/test
