name: Broken Links Check

on:
  - push

# on:
#   schedule:
#     - cron: '0 0 * * 0'

jobs:
  my-broken-link-checker:
    name: Broken Links Check
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://petrhurtak.com
          cmd_params: '--header="user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"'
