name: Broken Links Check

on:
  schedule:
    - cron: "0 12 * * 2,4,6" # At 12:00 on Tuesday, Thursday, and Saturday.

jobs:
  my-broken-link-checker:
    name: Broken Links Check
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://petrhurtak.com
          # Params docs https://github.com/raviqqe/muffet/blob/main/.snapshots/TestHelp
          #   `timeout`
          #     Increased because some links are on free Netlify or Heroku which can put the instances to sleep and it
          #     can take a long time for them to start again.
          #   `buffer-size`
          #     Increased otherwise it fails with "error when reading response headers: small read buffer".
          #   `exclude="https://www.linkedin.com"`
          #     Because LinkedIn returns 999 status code for bots.
          cmd_params: >
            --timeout=30
            --buffer-size=10000
            --exclude="https://www.linkedin.com"
            --color=always
            --verbose
