name: Broken Links Check

on:
  schedule:
    - cron: "0 12 * * 2,4,6" # At 12:00 on Tuesday, Thursday, and Saturday.

jobs:
  my-broken-link-checker:
    name: Broken Links Check
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://petrhurtak.com
          # buffer-size increased otherwise it fails with "error when reading response headers: small read buffer"
          # exclude of linkedin because it returns 999 status code
          cmd_params: >
            --verbose
            --color=always
            --buffer-size=10000
            --exclude="https://www.linkedin.com"
