name: Broken Links Check

on:
  - push

# on:
#   schedule:
#     - cron: '0 0 * * 0'

jobs:
  my-broken-link-checker:
    name: Broken Links Check
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://petrhurtak.com
          # cmd_params: "--one-page-only --max-connections=3 --color=always" # Check just one page
