name: Broken Links Check

on:
  - push

# on:
#   schedule:
#     - cron: '0 0 * * 0'

jobs:
  my-broken-link-checker:
    name: Broken Links Check
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://petrhurtak.com
          cmd_params: '--buffer-size=12000 --exclude="https://www.linkedin.com"'
